// Generated by gencpp from file custom_ros1_msg/CustomMessageExample.msg
// DO NOT EDIT!


#ifndef CUSTOM_ROS1_MSG_MESSAGE_CUSTOMMESSAGEEXAMPLE_H
#define CUSTOM_ROS1_MSG_MESSAGE_CUSTOMMESSAGEEXAMPLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_ros1_msg
{
template <class ContainerAllocator>
struct CustomMessageExample_
{
  typedef CustomMessageExample_<ContainerAllocator> Type;

  CustomMessageExample_()
    : name()
    , age(0)  {
    }
  CustomMessageExample_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessageExample_

typedef ::custom_ros1_msg::CustomMessageExample_<std::allocator<void> > CustomMessageExample;

typedef boost::shared_ptr< ::custom_ros1_msg::CustomMessageExample > CustomMessageExamplePtr;
typedef boost::shared_ptr< ::custom_ros1_msg::CustomMessageExample const> CustomMessageExampleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator1> & lhs, const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator1> & lhs, const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_ros1_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83da5ca00b8e049b0559653a472c88a5";
  }

  static const char* value(const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83da5ca00b8e049bULL;
  static const uint64_t static_value2 = 0x0559653a472c88a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_ros1_msg/CustomMessageExample";
  }

  static const char* value(const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
;
  }

  static const char* value(const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessageExample_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_ros1_msg::CustomMessageExample_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_ROS1_MSG_MESSAGE_CUSTOMMESSAGEEXAMPLE_H
